on:
  push:
    branches:
      - "*"
      - "!master"

name: Development
jobs:
  build:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: xcodebuild clean && xcodebuild test -project MultipartFormData.xcodeproj -scheme MultipartFormDataTests
